name: Check Markdown links

on:
  push:
  schedule:
    - cron: '0 14 * * 2' # 2pm Tuesday

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          config-file: 'mlc_config.json'
